# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

r_packages:
  - tidyverse
  - bookdown
  - here

#install:
#  - ./travis-tool.sh install_aptget r-cran-tidyverse r-cran-bookdown r-cran-here

script:
  - ./render_books.sh
